### ISSUE TITLE
way to update the app

### ISSUE THREAD

**Issue by legacychimera247** [roundedrectangle/SailDiscord#1]
Hello, and thanks for developing a discord app

been wondering, if i try the app i have no way to update it other than rebuilding the package, right?

discord is so damn slow on my xa2 we really needed a native app...

**Comment by roundedrectangle** [comment]
Hello, the app is in an early stage of development, and I am not currently writing it. It can only display your server names and username for now. If you still wanna try it, then you can do so by downloading sailfish ide and building it. Updating is done by installing the new version of package you rebuild, but as I said earlier do not expect updates for now. I have no ETAs.

**Comment by roundedrectangle** [comment]
Also my main device is not a sfos device rn

**Comment by roundedrectangle** [comment]
You can ask me if you will have problems with building

**Comment by legacychimera247** [comment]
I can't test it right now unfortunately, the sailfish sdk is asking me for a virtual machine installed and right now i only have boxes, which is not supported, so couldn't install it

i'll wait for someone from the community to build it...

**Comment by roundedrectangle** [comment]
You should use VirtualBox or docker to build. If you want I can build the current version for you

**Comment by legacychimera247** [comment]
That would be very nice of you, thank you

Il Sabato 13 luglio 2024, roundedrectangle scrive:
> You should use VirtualBox or docker to build. If you want I can build the current version for you
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/roundedrectangle/SailDiscord/issues/1#issuecomment-2226824025
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***

-- 
Inviato dal mio dispositivo Sailfish

**Comment by roundedrectangle** [comment]
I published two releases, one has some glitches with pictures, the other one does not include pictures so no glitches are there.

**Comment by legacychimera247** [comment]
Thank you, very nice

have you ever thought about publish the thing on the forum?maybe some other dev could help you :)

**Comment by roundedrectangle** [comment]
No, I don't think so.

I don't have any problems developing the app except my only SailfishOS phone being Jolla C which is old and not my daily driver. I won't accept any donations at least for now because I might just be lazy. I am thinking now of buying an Xperia, but these are very hard to find in my country. I might even try to port sailfishos to my phone, but my computer is not very fast and has only 30 out of 128gb of free storage.

After all, the app has very limited functionality. I will publish the app to forum if it will at least have servers functionality (channels, messages, etc.).

**Comment by roundedrectangle** [comment]
And yeah, if you want you can join my discord [here](https://discord.gg/Q3u7ejjzFg). It is almost empty for now, but already has downloads, annoucments and a text channel.

**Comment by legacychimera247** [comment]
honestly, i would only need messages to work, it's the only thing i would be interested for now, don't need extra things like calls and whatever, just text messages and pictures/gifs

i would already be happy this way :)

anyway, will join your channel, thank you...

**Comment by legacychimera247** [comment]
anyway, i guess i can close this one

**Comment by roundedrectangle** [comment]
Yeah of course, check the server btw

**Comment by roundedrectangle** [comment]
Hello, please join my new telegram [channel](https://t.me/saildiscord) for this app. I decided that a server could get us banned so telegram is where news will be from now on. The server will still be used for testing.
