### ISSUE TITLE
Login via web view does not seem to work in v0.4.1

### ISSUE THREAD

**Issue by RaphaelWimmer** [roundedrectangle/SailDiscord#10]
I started v0.4.1 on SFOS 4.5.
The login screen shows a loading animation (circle) for a few seconds, then only a white screen remains.
Using my token, I could login. However, then the screen was stuck on "Loading..." (or similar). 
After a while, I restarted the app - then it immediately loaded the server list.

**Comment by RaphaelWimmer** [comment]
nvm, just saw that there is a newer version with various fixes

**Comment by roundedrectangle** [comment]
Yeah, I pushed an update without checking if it works in SailJail. But quickly pushed a fix. Just use 0.4.2
